### ISSUE TITLE
希望可以一起共建

### ISSUE THREAD

**Issue by Viyond** [li-xiao-shuang/serviceplus#10]
有没有一些设计思路，可以一起共建呢，人多力量大，希望可以一起合作

**Comment by li-xiao-shuang** [comment]
> 有没有一些设计思路，可以一起共建呢，人多力量大，希望可以一起合作

热烈欢迎  老哥可以添加下我微信 lx6688s  我们一起探讨下

**Comment by li-xiao-shuang** [comment]
> 有没有一些设计思路，可以一起共建呢，人多力量大，希望可以一起合作

你有什么想法也可以说说
